name: Add Approved Video

on:
  issues:
    types: [closed]

jobs:
  add:
    if: contains(github.event.issue.labels.*.name, 'submission') && contains(github.event.issue.labels.*.name, 'submission approved')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm i @octokit/request
          node ./scripts/add-video.js "${{ github.event.issue.number }}" "${{ github.repository }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "./public/submissions.json"
          git commit -m "Automatically added a video to submissions.json"
          git push origin new-main