# When closing an issue with both the 'submission' and 'submission approved' labels, this adds the video to the master submissions.json list.
name: Add Approved Video

on:
  issues:
    types: [closed]

jobs:
  add:
    if: contains(github.event.issue.labels.*.name, 'submission') && contains(github.event.issue.labels.*.name, 'submission approved')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          # add-video.js requires @octokit/request
          npm i @octokit/request
          
          # Run the add-video.js script to update submissions.json; requires the issue number of the issue closed and the repo name
          # to get the body contents of the issue
          node ./scripts/add-video.js "${{ github.event.issue.number }}" "${{ github.repository }}"

          # Commit the updated submissions.json
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "submissions.json"
          git commit -m "Automatically added a video to submissions.json"
          git push origin new-main