name: Create Submission PR

on:
  repository_dispatch:
    types: [new-submission]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create file
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "submission.json"
          json: ${{ github.event.client_payload }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ github.event.client_payload.title }}
