name: Create Submission PR

on:
  repository_dispatch:
    types: [new-submission]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ${{ github.event.client_payload }} | jq '.'
