name: Create Submission PR

on:
  repository_dispatch:
    types: [new-submission]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: 'node ./.github/scripts/create.js DATA="${{ toJson(github.event.client_payload) }}"'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: ${{ github.event.client_payload.title }}
