name: Sync Submissions List

on:
  # push:
  #   branches: ['main']
  #   paths:
  #     - 'submissions.json'
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: windows-latest
    steps:
      # fetch-depth: 0 used here to checkout both branches. Is there a better way?
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          git checkout main submissions.json
          git add submissions.json
          git commit -m "Automatically updated submissions.json"
          git push origin gh-pages