# Syncs the videos.json file from the main branch to gh-pages branch to be read by the deployed site.
name: Sync Videos List

on:
  # On push may be appropriate to be deleted later; this was meant to immediately sync the videos.json file
  # after directly editing it when I was testing
  # push:
  #   branches: ['new-main']
  #   paths:
  #     - 'videos.json'
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  # Or with the correct access token, it can be triggered with a GitHub API call
  repository_dispatch:
    types: [sync]

jobs:
  sync:
    runs-on: windows-latest
    steps:
      # fetch-depth: 0 used here to checkout both branches. Is there a better way? Used in deploy.yml as well.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout gh-pages
          git checkout new-main videos.json
          git checkout new-main scripts/get-manim-versions.js
          node ./scripts/get-manim-versions.js
          git reset -- scripts
          git add videos.json
          git add manim-versions.json
          git commit -m "Automatically updated videos.json and checked Manim releases"
          git push origin gh-pages
